### ISSUE TITLE
Auth0 Authenticator doesn't work with PUBLIC_ACCESS

### ISSUE THREAD

**Issue by RarstManPL** [auth0/symfony#154]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/symfony#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/symfony/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I would like to achieve something like this, so that all routes are available to both logged in and non-logged in users. 

For this purpose:

1. in the access_control key in the security.yaml file, I set the roles to **PUBLIC_ACCESS** for all routes. 
2. similarly, in the firewalls section, I set provider **auth0_provider** (according to the documentation) and **auth0.authenticator** (in the custom_authenticators section) for all routes. 

Unfortunately, anonymous users cannot access the site (they are immediately redirected to the auth0 login page). I also cannot opt out of the auth0 provider for these routes, because I want to be able to retrieve information about the user when he is logged in.

This is my security.yaml file:

```
security:
    providers:
        auth0_provider:
            id: Auth0\Symfony\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        auth0:
            pattern: ^/(?!login|callback|logout).*
            provider: auth0_provider
            custom_authenticators:
                - auth0.authenticator
        main:
            lazy: true

    access_control:
        - { path: ^/.*, roles: PUBLIC_ACCESS }
```

### Reproduction

1. I set the configuration as above
2. I'm trying to access the site as an anonymous user
3. I am redirected to the auth0 login page

### jwt-auth-bundle version

-

### Symfony version

6.2

### PHP version

8.2
