### ISSUE TITLE
How to user credentials from stateless authorization 

### ISSUE THREAD

**Issue by alebedev80** [auth0/symfony#157]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/symfony#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/symfony/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'm developing SPA + API service. SPA get data from API with token in the request. I need to get on API side user details especially `email` and `email_verified` but from instance of  User object i'm able to get Auth0 user id and some dates info only. How to get user's email?

Me configuration:

```
# auth0.yaml:

auth0:
    sdk:
        strategy: "none"
        domain: "%env(trim:string:AUTH0_DOMAIN)%"
        client_id: "%env(trim:string:AUTH0_CLIENT_ID)%"
        client_secret: "%env(trim:string:AUTH0_CLIENT_SECRET)%"
        cookie_secret: "%env(trim:string:AUTH0_COOKIE_SECRET)%"
        # custom_domain: "%env(trim:string:AUTH0_CUSTOM_DOMAIN)%"
        audiences:
            - "%env(trim:string:AUTH0_API_AUDIENCE)%"

        scopes:
            - openid
            - profile
            - email
            - offline_access

        token_cache_ttl: 3600

    authenticator:
        routes:
            callback: "%env(string:AUTH0_ROUTE_CALLBACK)%"
            success: "%env(string:AUTH0_ROUTE_SUCCESS)%"
            failure: "%env(string:AUTH0_ROUTE_FAILURE)%"
            login: "%env(string:AUTH0_ROUTE_LOGIN)%"
            logout: "%env(string:AUTH0_ROUTE_LOGOUT)%"
```

```
# security.yaml

security:
    providers:
        users_in_memory: { memory: null }
        auth0_provider:
            id: Auth0\Symfony\Security\UserProvider

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|success|failed)/
            security: false

        api:
            pattern: ^/greetings$ # A pattern example for stateless (token-based authorization) route requests
            stateless: true
            provider: auth0_provider
            custom_authenticators:
                - auth0.authorizer

        main:
            lazy: true
            provider: users_in_memory

    access_control:
        - { path: ^/greetings$, roles: ROLE_USING_TOKEN }
```

```
# App\EventSubscriber\PostAuthSubscriber

<?php

declare(strict_types=1);

namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Security\Core\Event\AuthenticationSuccessEvent;

readonly class PostAuthSubscriber implements EventSubscriberInterface

{

    public function onSecurityAuthenticationSuccess(AuthenticationSuccessEvent $event): void
    {
        $user = $event->getAuthenticationToken()->getUser();
        die(print_r($user, true));
    }

    public static function getSubscribedEvents(): array
    {
        return [
            'security.authentication.success' => 'onSecurityAuthenticationSuccess',
        ];
    }
}
```

Result:

```
Auth0\Symfony\Models\Stateless\User Object
(
    [roleAuthenticatedUsing:protected] => ROLE_USING_TOKEN
    [roles:protected] => Array
        (
            [0] => IS_AUTHENTICATED_FULLY
            [1] => ROLE_USER
        )

    [data:Auth0\Symfony\Models\User:private] => Array
        (
            [iss] => https://dev-1oh165tc42mnsf2b.eu.auth0.com/
            [sub] => auth0|65096f6331400f906dce8f4f
            [aud] => Array
                (
                    [0] => https://test.wemono.com
                    [1] => https://dev-1oh165tc42mnsf2b.eu.auth0.com/userinfo
                )

            [iat] => 1695213041
            [exp] => 1695299441
            [azp] => dRSQZliThdmR9MbodIBLEoYIw5nqq9Jw
            [scope] => openid profile email
        )

)
```

### Describe the ideal solution

Will  be good to get that data in by call the method '$user->getEmail()'.
