### ISSUE TITLE
Authorizer doesn't support requests without token

### ISSUE THREAD

**Issue by alebedev80** [auth0/symfony#158]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/symfony#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/symfony/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I think method `Auth0\Symfony\Security\Authorizer::supports()` should always return `true`.

```
    public function supports(Request $request): ?bool
    {
        return null !== $request->get('token') || ($request->headers->has('Authorization') && stripos((string) $request->headers->get('Authorization'), 'Bearer ') === 0);
    }
```

Because 
a) no token in a request is the same as invalid token
b) there are proper token validations in the method `Auth0\Symfony\Security\Authorizer::authenticate()`:

```
        // Ensure the 'authorization' header is present in the request
        if ('' === $token) {
            throw new AuthenticationException('`Authorization` header not present.');
        }

        // Ensure the 'authorization' header includes a bearer prefixed JSON web token.
        if ($usingHeader && 0 !== stripos($token, 'bearer ')) {
            throw new AuthenticationException('`Authorization` header is malformed.');
        }

```

### Reproduction

1. Setup symfony
2. setup firewall
```
    firewalls:
        api:
            pattern: ^/.+ # A pattern example for stateless (token-based authorization) route requests
            stateless: true
            provider: auth0_provider
            custom_authenticators:
               - auth0.authorizer
```

### jwt-auth-bundle version

-

### Symfony version

6.3

### PHP version

8.2
